### PR TITLE
fix: [534] fix Webpack warning on named imports from json files

### PR DESCRIPTION
**Pull request by dg-harris**
# Github Issue or Trello Card
This PR addresses this issue: #534 

This PR is just a demonstration of the current webpack 5 issues caused due to named import from json: https://webpack.js.org/blog/2020-10-10-webpack-5-release/#json-modules
as well as a possible solution.

test-project is just a create-react-app (which uses webpack5) that imports the locally built version of palmetto components. You can see the webpack errors by reverting the changes to token.ts and running `npm start` inside test-project. I've also attached screenshots of the changes below.

If the changes I've made to token.ts are acceptable as-is I can remove test-project from this PR and remove the do not merge label.

### Before
Screen Shot 2021-12-15 at 10 59 17 AM

### After
Screen Shot 2021-12-15 at 11 02 26 AM

# What type of change is this?
Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updating documentation.
- [ ] Updating deployment/build pipeline.
- [ ] Updating Project Dependencies
- [ ] Improving or adding to Test Coverage

# Completeness Checklist

- [ ] TESTS: My changes maintain the baseline required test coverage, as specified by code climate analysis.
- [ ] DOCS: All new component work is covered in that component's `Overview` docs.
- [ ] DOCS: All new component work is covered in a component `Playground`.
- [ ] DOCS: All new visual changes or options are covered under relevant components' `VisualTests`.
- [ ] My code has no linting or typescript compile warnings.
- [ ] My work is tied to a Github issue and satisfies the acceptance criteria (if applicable) of the corresponding issue.

# Quality Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# UI Checklist
- [ ] I have conducted visual UAT on my changes/features.
- [ ] My solution works well on desktop, tablet, and mobile browsers.

### CODE REVIEW

**Comment by juanfabrega** [comment]
Hey @dg-harris this is totally fine with me provided all the build jobs, tests, as well as the storybook run properly, which seems to be the case here. 

Feel free to remove the test-project and we can get this merged.

**Comment by dg-harris** [comment]
Hey sorry I wasn't sure what the procedure was, should I be merging this?

**Comment by surfjedi** [comment]
Yeah I was trying to use this and got the same errors on my first import

**Comment by surfjedi** [comment]
And you can install from this branch either FYI
Screen Shot 2022-01-03 at 8 54 03 PM

**Pull request merged**
